name: ci

on:
  push:

jobs:
  docker:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:dind
        options: --privileged --shm-size=2g
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock:ro
    container:
      image: ubuntu:latest
    steps:
      # - id: docker-setup
      #   name: Set up Docker
      #   uses: docker/setup-docker-action@v4
      #   with:
      #     daemon-config: |
      #       {
      #         "debug": true,
      #         "features": {
      #           "containerd-snapshotter": true
      #         }
      #       }

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Checkout repository
        uses: actions/checkout@v4

      - id: vars
        name: Set short git commit SHA
        run: |
          calculatedSha=$(git rev-parse --short ${{ github.sha }})
          echo "COMMIT_SHORT_SHA=$calculatedSha" >> $GITHUB_OUTPUT

      - name: Build an image from Dockerfile
        run: |
          docker buildx build --platform=linux/amd64,linux/arm64 --no-cache --output type=docker --load -t docker.io/${{ secrets.DOCKERHUB_USERNAME }}/hello:${{ steps.vars.outputs.COMMIT_SHORT_SHA }} .

          docker images

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.29.0
        with:
          image-ref: 'docker.io/${{ secrets.DOCKERHUB_USERNAME }}/hello:${{ steps.vars.outputs.COMMIT_SHORT_SHA }}'
          # docker-host: ${{ steps.docker-setup.outputs.sock }}
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          scanners: vuln
          vuln-type: 'os'
          severity: 'CRITICAL,HIGH'
          timeout: '30m'

      - name: Push an image to docker.io
        run: |
          docker image push docker.io/${{ secrets.DOCKERHUB_USERNAME }}/hello:${{ steps.vars.outputs.COMMIT_SHORT_SHA }}
